### ISSUE TITLE
Any experiment can account for the fluency of the generated results?

### ISSUE THREAD

**Issue by bb9696aa** [Evan-Gao/Distractor-Generation-RACE#2]
The idea of this paper is fantastic! 
I notice that both human evaluation and automatic evalution do not include the assessment of the fluency of the generated sequences. 
So I'm confused about the actual effect of the 'question-based initializer' and 'dynamic attention' on generating more readable sequences.

**Comment by Evan-Gao** [comment]
Your concern is reasonable. We will consider adding more comparison experiments in the future.
